import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col justify-center w-full max-h-screen max-w-screen-lg m-auto`}
      >
        <div className="w-full flex justify-between px-12">
          <Link href="/page2">pagina 2</Link>
          <Link href="/boas-vindas">boas vindas</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
